language: ruby
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
cache: bundler
rvm:
  - 2.6.0
services:
  - postgresql
env:
  - DB=postgres
before_script:
  - cp config/database.yml.travis config/database.yml
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec
  - whereis google-chrome-stable
  - whereis chromedriver