language: ruby
cache: bundler
rvm:
  - 2.6.0
services:
  - postgresql
env:
  - DB=postgres
before_script:
  - cp config/database.yml.travis config/database.yml
  - google-chrome --version
before_install:
  - google-chrome --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
sudo: required
dist: trusty
addons:
  chrome: stable
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec