language: ruby
cache: bundler
rvm:
  - 2.6.0
chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable
matrix:
  include:
    - env: CHROME=1 TASK=//rb:chrome-test
      <<: *ruby
      <<: *chrome
install: ./scripts/travis/install.sh
env:
  - DB=postgres
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec