language: ruby
rvm:
  - 2.6.0
services:
  - postgresql
addons:
  postgresql: "11.3"
  apt:
      packages:
      - postgresql-11.3
      - postgresql-client-11.3
env:
  global:
  - PGPORT=5432
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec spec/