language: ruby
addons:
  apt:
    - google-chrome-stable
    - chromium-chromedriver
cache: bundler
rvm:
  - 2.6.0
services:
  - postgresql
env:
  - DB=postgres
before_script:
  - cp config/database.yml.travis config/database.yml
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec